// Zero-dependency, XSS-safe markdown renderer for the ELIZA-AI web UI.
// Local-first: no CDN, no npm packages. Renders the subset LLMs emit most:
// headings, bold/italic/strikethrough, inline + fenced code, lists (incl.
// task lists + nesting), blockquotes, hr, links, images, tables, paragraphs.
//
// Safety model: raw HTML is NEVER passed through. Everything is escaped
// first; only tags generated by this renderer exist in the output. URLs are
// allow-listed (http/https/mailto/anchor/relative); anything else (e.g.
// `javascript:`, `data:`) degrades to plain text.

export function escHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => {
    switch (c) {
      case "&": return "&amp;";
      case "<": return "&lt;";
      case ">": return "&gt;";
      case '"': return "&quot;";
      case "'": return "&#39;";
      default: return c;
    }
  });
}

function isSafeUrl(url: string): boolean {
  const u = url.trim();
  if (!u) return false;
  if (u.startsWith("#") || u.startsWith("/") || u.startsWith("./") || u.startsWith("../")) return true;
  if (/^[a-zA-Z0-9._~:/?#[\]@!$&'()*+,;=%-]+$/.test(u) === false) {
    // Allow unicode-ish URLs too; only block control chars / spaces / quotes.
    if (/[\s<>"'`]/.test(u)) return false;
  }
  const lower = u.toLowerCase();
  if (lower.startsWith("https://") || lower.startsWith("http://") || lower.startsWith("mailto:")) return true;
  // Relative URL without scheme (e.g. `docs/guide`, `page.html?a=b`).
  if (/^[a-z0-9._~/?#[\]@!$&'()*+,;=%-]+$/i.test(u) && !/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(u)) return true;
  return false;
}

/**
 * GitHub-style emoji shortcodes (`:rocket:` → 🚀). Zero-dependency table so
 * the local-first web UI needs no CDN. Deliberately no all-digit keys so
 * times like `10:30` are never mangled; unknown codes stay literal.
 */
export const EMOJI_SHORTCODES: Record<string, string> = {
  // Smileys & faces
  grinning: "😀", smiley: "😃", smile: "😄", grin: "😁", laughing: "😆",
  sweat_smile: "😅", joy: "😂", rofl: "🤣", wink: "😉", blush: "😊",
  yum: "😋", sunglasses: "😎", heart_eyes: "😍", kissing_heart: "😘",
  thinking: "🤔", neutral_face: "😐", expressionless: "😑", no_mouth: "😶",
  confused: "😕", slightly_smiling_face: "🙂", slightly_frowning_face: "🙁",
  cry: "😢", sob: "😭", open_mouth: "😮", astonished: "😲", scream: "😱",
  sleeping: "😴", zzz: "💤", mask: "😷", star_struck: "🤩", nerd_face: "🤓",
  robot: "🤖", ghost: "👻", alien: "👽", skull: "💀", clown_face: "🤡",
  partying_face: "🥳", poop: "💩",
  // Gestures & people
  "+1": "👍", thumbsup: "👍", "-1": "👎", thumbsdown: "👎",
  ok_hand: "👌", pray: "🙏", clap: "👏", wave: "👋", handshake: "🤝",
  fist: "👊", v: "✌️", crossed_fingers: "🤞", muscle: "💪",
  point_up: "☝️", point_right: "👉", raised_hands: "🙌", eyes: "👀",
  brain: "🧠", speaking_head: "🗣️",
  // Love, celebration, effects
  heart: "❤️", orange_heart: "🧡", yellow_heart: "💛", green_heart: "💚",
  blue_heart: "💙", purple_heart: "💜", black_heart: "🖤", white_heart: "🤍",
  broken_heart: "💔", heartbeat: "💓", heartpulse: "💗",
  star: "⭐", sparkles: "✨", fire: "🔥", tada: "🎉", balloon: "🎈",
  gift: "🎁", trophy: "🏆", medal: "🏅",
  // Tech & objects
  rocket: "🚀", bulb: "💡", books: "📚", book: "📖", memo: "📝",
  pencil: "✏️", computer: "💻", keyboard: "⌨️", gear: "⚙️",
  wrench: "🔧", hammer: "🔨", mag: "🔍", lock: "🔒", unlock: "🔓",
  key: "🔑", link: "🔗", package: "📦", inbox_tray: "📥",
  outbox_tray: "📤", wastebasket: "🗑️", file_folder: "📁", page_facing_up: "📄",
  bar_chart: "📊", calendar: "📅", alarm_clock: "⏰", hourglass: "⏳",
  moneybag: "💰", dollar: "💵", credit_card: "💳",
  // Symbols
  white_check_mark: "✅", check: "✅", heavy_check_mark: "✔️",
  x: "❌", warning: "⚠️", information_source: "ℹ️", question: "❓",
  exclamation: "❗", no_entry: "⛔", red_circle: "🔴", large_blue_circle: "🔵",
  white_circle: "⚪", black_circle: "⚫", arrow_right: "➡️",
  arrow_left: "⬅️", arrow_up: "⬆️", arrow_down: "⬇️", recycle: "♻️",
  construction: "🚧",
  // Nature, animals, food
  sunny: "☀️", crescent_moon: "🌙", cloud: "☁️", rain_cloud: "🌧️",
  snowflake: "❄️", zap: "⚡", ocean: "🌊", earth_americas: "🌍",
  seedling: "🌱", cherry_blossom: "🌸", dog: "🐶", cat: "🐱",
  bug: "🐛", ladybug: "🐞", penguin: "🐧", coffee: "☕",
  pizza: "🍕", hamburger: "🍔", apple: "🍎", beer: "🍺",
  birthday: "🎂", cookie: "🍪",
};

/** Expand `:shortcode:` occurrences; unknown codes are left as-is. */
export function expandEmojiShortcodes(s: string): string {
  return s.replace(/:([a-z0-9_+-]+):/g, (m, name: string) => EMOJI_SHORTCODES[name] ?? m);
}

type Fence = { lang: string; code: string };
type InlineCode = { code: string };

const FENCE_PH = "\u0000FENCE";
const ICODE_PH = "\u0000ICODE";

function renderInline(src: string, inlineCodes: InlineCode[]): string {
  // src is already HTML-escaped, except placeholders.
  // Shortcodes expand on text only: code spans/fences live in placeholders
  // (no colons), so `:smile:` inside code is never converted.
  let out = expandEmojiShortcodes(src);

  // Restore-then-wrap inline code first so no other inline rule touches it.
  out = out.replace(new RegExp(`${ICODE_PH}(\\d+)\u0000`, "g"), (_m, n) => {
    const entry = inlineCodes[Number(n)];
    const code = entry ? escHtml(entry.code) : "";
    return `<code>${code}</code>`;
  });

  // Images: ![alt](url "optional title"). URL allows one level of balanced parens.
  const URL_IN_PARENS = String.raw`((?:[^()\s]|\([^()]*\))+)`;
  out = out.replace(new RegExp(`!\\[([^\\]]*)\\]\\(\\s*${URL_IN_PARENS}(?:\\s+"[^"]*")?\\s*\\)`, "g"), (_m, alt, url) => {
    if (!isSafeUrl(url)) return escHtml(`![${alt}](${url})`);
    return `<img src="${escHtml(url)}" alt="${escHtml(alt)}" loading="lazy" />`;
  });

  // Autolinks: <https://...> and <user@mail>.
  out = out.replace(/&lt;(https?:\/\/[^<>\s]+|mailto:[^<>\s]+)&gt;/g, (_m, url) => {
    const raw = url.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'");
    if (!isSafeUrl(raw)) return _m;
    return `<a href="${escHtml(raw)}" target="_blank" rel="noopener noreferrer">${escHtml(raw)}</a>`;
  });

  // Links: [text](url). Text may contain bold/italic — process recursively-ish by running
  // emphasis passes afterwards (they operate on the whole string, and link text has no brackets left).
  out = out.replace(new RegExp(`\\[([^\\]]+)\\]\\(\\s*${URL_IN_PARENS}(?:\\s+"[^"]*")?\\s*\\)`, "g"), (_m, text, url) => {
    if (!isSafeUrl(url)) return `${escHtml(text)}`;
    return `<a href="${escHtml(url)}" target="_blank" rel="noopener noreferrer">${text}</a>`;
  });

  // Bare URLs (not already inside href="...").
  out = out.replace(/(^|[\s(])(https?:\/\/[^\s<>"']+)/g, (_m, pre, url) => {
    const clean = url.replace(/[.,;:!?]+$/, "");
    const trail = url.slice(clean.length);
    if (!isSafeUrl(clean)) return _m;
    return `${pre}<a href="${escHtml(clean)}" target="_blank" rel="noopener noreferrer">${escHtml(clean)}</a>${trail}`;
  });

  // Strikethrough ~~x~~.
  out = out.replace(/~~([^~\n]+?)~~/g, "<del>$1</del>");
  // Bold **x** and __x__.
  out = out.replace(/\*\*([^*\n]+?)\*\*/g, "<strong>$1</strong>");
  out = out.replace(/__([^_\n]+?)__/g, "<strong>$1</strong>");
  // Italic *x* and _x_ (after bold so ** doesn't partially match).
  out = out.replace(/(^|[\s(\[{>"'])_([^_\n]+?)_([\s).,\]}<'"?!;:-]|$)/g, "$1<em>$2</em>$3");
  out = out.replace(/(^|[\s(\[{>"'])\*([^*\n]+?)\*([\s).,\]}<'"?!;:-]|$)/g, "$1<em>$2</em>$3");

  return out;
}

function splitTableRow(row: string): string[] {
  let r = row.trim();
  if (r.startsWith("|")) r = r.slice(1);
  if (r.endsWith("|")) r = r.slice(0, -1);
  // Split on unescaped pipes.
  const cells: string[] = [];
  let cur = "";
  let escaped = false;
  for (const ch of r) {
    if (escaped) { cur += ch; escaped = false; continue; }
    if (ch === "\\") { escaped = true; continue; }
    if (ch === "|") { cells.push(cur); cur = ""; continue; }
    cur += ch;
  }
  cells.push(cur);
  return cells.map((c) => c.trim());
}

function isDelimiterRow(cells: string[]): boolean {
  return cells.length > 0 && cells.every((c) => /^:?-+:?$/.test(c));
}

function alignOf(cell: string): string {
  const left = cell.startsWith(":");
  const right = cell.endsWith(":");
  if (left && right) return "center";
  if (right) return "right";
  if (left) return "left";
  return "";
}

/** Render markdown to safe HTML. Output is a fragment (no <html> wrapper). */
export function renderMarkdown(source: string): string {
  if (!source) return "";
  let text = source.replace(/\r\n?/g, "\n");

  // 1. Extract fenced code blocks (``` or ~~~) before escaping.
  const fences: Fence[] = [];
  text = text.replace(/(^|\n)(`{3,}|~{3,})[ \t]*([^\n]*)\n([\s\S]*?)\n?[ \t]*\2[ \t]*(?=\n|$)/g,
    (_m, pre, _f, lang, code) => {
      const idx = fences.length;
      fences.push({ lang: (lang || "").trim().split(/\s+/)[0] ?? "", code: code.replace(/\n$/, "") });
      return `${pre}${FENCE_PH}${idx}\u0000`;
    });
  // Unclosed fence at EOF: treat rest of input as code (common while streaming,
  // and graceful for truncated LLM output).
  text = text.replace(/(^|\n)(`{3,}|~{3,})[ \t]*([^\n]*)\n([\s\S]*)$/g,
    (_m, pre, _f, lang, code) => {
      const idx = fences.length;
      fences.push({ lang: (lang || "").trim().split(/\s+/)[0] ?? "", code: code.replace(/\n$/, "") });
      return `${pre}${FENCE_PH}${idx}\u0000`;
    });

  // 2. Extract inline code spans before escaping.
  const icodes: InlineCode[] = [];
  text = text.replace(/(`+)([^`\n]*?)\1/g, (_m, _ticks, code) => {
    const idx = icodes.length;
    icodes.push({ code });
    return `${ICODE_PH}${idx}\u0000`;
  });

  // 3. Escape everything else (placeholders survive: they are \u0000 + A-Z0-9).
  text = escHtml(text);

  const lines = text.split("\n");
  const html: string[] = [];
  let para: string[] = [];
  // List stack for nesting: each entry {type, indent}.
  let listStack: { type: "ul" | "ol"; indent: number }[] = [];

  const flushPara = () => {
    if (para.length === 0) return;
    const joined = para.join("\n").replace(/\n/g, "<br />");
    html.push(`<p>${renderInline(joined, icodes)}</p>`);
    para = [];
  };
  const closeLists = (minIndent = 0) => {
    while (listStack.length > 0 && listStack[listStack.length - 1]!.indent >= minIndent) {
      const l = listStack.pop()!;
      html.push(`</${l.type}>`);
    }
  };

  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!;
    const trimmed = line.trim();

    // Fenced code placeholder on its own line.
    const fenceMatch = trimmed.match(new RegExp(`^${FENCE_PH}(\\d+)\u0000$`));
    if (fenceMatch) {
      flushPara();
      closeLists();
      const f = fences[Number(fenceMatch[1])]!;
      const langCls = f.lang ? ` class="language-${escHtml(f.lang)}"` : "";
      const langLbl = f.lang ? `<span class="code-lang">${escHtml(f.lang)}</span>` : "";
      html.push(
        `<div class="codeblock"><div class="code-head">${langLbl}<button type="button" class="copy-btn" data-code-copy title="Copy code">copy</button></div>` +
        `<pre><code${langCls}>${escHtml(f.code)}</code></pre></div>`
      );
      i++;
      continue;
    }

    if (trimmed === "") {
      flushPara();
      i++;
      continue;
    }

    // ATX headings.
    const h = trimmed.match(/^(#{1,6})\s+(.+?)\s*#*\s*$/);
    if (h) {
      flushPara();
      closeLists();
      const level = h[1]!.length;
      html.push(`<h${level}>${renderInline(h[2]!, icodes)}</h${level}>`);
      i++;
      continue;
    }

    // Horizontal rule.
    if (/^(\*\*\*+|---+|___+)\s*$/.test(trimmed)) {
      flushPara();
      closeLists();
      html.push("<hr />");
      i++;
      continue;
    }

    // Tables: header + delimiter + >=0 body rows.
    if (trimmed.includes("|") && i + 1 < lines.length) {
      const headCells = splitTableRow(trimmed);
      const delimCells = splitTableRow((lines[i + 1] ?? "").trim());
      if (headCells.length > 0 && delimCells.length === headCells.length && isDelimiterRow(delimCells)) {
        flushPara();
        closeLists();
        const aligns = delimCells.map(alignOf);
        html.push("<div class=\"table-wrap\"><table><thead><tr>" +
          headCells.map((c, k) => {
            const a = aligns[k] ? ` align="${aligns[k]}"` : "";
            return `<th${a}>${renderInline(c, icodes)}</th>`;
          }).join("") + "</tr></thead><tbody>");
        i += 2;
        while (i < lines.length && (lines[i] ?? "").trim().includes("|")) {
          const body = splitTableRow((lines[i] ?? "").trim());
          if (body.length === 0) break;
          html.push("<tr>" + headCells.map((_, k) => {
            const a = aligns[k] ? ` align="${aligns[k]}"` : "";
            return `<td${a}>${renderInline(body[k] ?? "", icodes)}</td>`;
          }).join("") + "</tr>");
          i++;
        }
        html.push("</tbody></table></div>");
        continue;
      }
    }

    // Blockquote: gather consecutive > lines, strip one level, recurse.
    if (/^&gt;/.test(trimmed) || trimmed.startsWith(">")) {
      flushPara();
      closeLists();
      const quoteLines: string[] = [];
      while (i < lines.length) {
        const l = (lines[i] ?? "").trim();
        if (!/^(&gt;|>)/.test(l)) break;
        quoteLines.push(l.replace(/^(&gt;|>)\s?/, ""));
        i++;
      }
      // Unescape &gt; back to > for nested parsing, then re-run renderer on inner text.
      const innerSrc = quoteLines.join("\n").replace(/&gt;/g, ">").replace(/&lt;/g, "<").replace(/&amp;/g, "&");
      // Inner text contains no fences placeholders escaping issues: re-escape handled by recursive call.
      // But placeholders for code were already escaped — decode them? Simpler: render inner via renderMarkdown
      // on the unescaped source only when no placeholders present; otherwise render inline.
      if (innerSrc.includes(FENCE_PH) || innerSrc.includes(ICODE_PH)) {
        html.push(`<blockquote><p>${renderInline(quoteLines.join("<br />"), icodes)}</p></blockquote>`);
      } else {
        // NOTE: innerSrc at this point is escaped-text-decoded; inline code entries were extracted
        // from the outer pass so a recursive call would double-escape. Render inline only.
        html.push(`<blockquote><p>${renderInline(quoteLines.join("<br />"), icodes)}</p></blockquote>`);
      }
      continue;
    }

    // Lists: `-`, `*`, `+`, `1.` / `1)`; indent = leading spaces.
    const listMatch = line.match(/^(\s*)([-*+]|\d+[.)])\s+(.*)$/);
    if (listMatch) {
      flushPara();
      const indent = listMatch[1]!.replace(/\t/g, "  ").length;
      const marker = listMatch[2]!;
      const rawContent = listMatch[3] ?? "";
      const type: "ul" | "ol" = /^\d/.test(marker) ? "ol" : "ul";

      // Close deeper lists, open new nesting as needed.
      while (listStack.length > 0 && indent < listStack[listStack.length - 1]!.indent) {
        html.push(`</${listStack.pop()!.type}>`);
      }
      const top = listStack[listStack.length - 1];
      if (!top || indent > top.indent || top.type !== type) {
        // Same-level type switch: close the current list first.
        if (top && indent === top.indent && top.type !== type) {
          html.push(`</${listStack.pop()!.type}>`);
        }
        html.push(`<${type}>`);
        listStack.push({ type, indent });
      }

      // Task list: - [ ] / - [x].
      let content = rawContent;
      let checkbox = "";
      const task = rawContent.match(/^\[([ xX])\]\s+(.*)$/);
      if (type === "ul" && task) {
        const checked = task[1]!.toLowerCase() === "x";
        checkbox = `<input type="checkbox" disabled${checked ? " checked" : ""} /> `;
        content = task[2] ?? "";
      }
      // Ordered marker start: continue numbering naturally via <ol> (no explicit start handling needed
      // except when the first marker isn't 1).
      html.push(`<li>${checkbox}${renderInline(content, icodes)}</li>`);
      i++;
      // If next line is not a list item and not blank, keep list open (paragraph continuation ignored simply).
      const next = lines[i];
      if (next === undefined || (next.trim() !== "" && !/^(\s*)([-*+]|\d+[.)])\s+/.test(next))) {
        // Peek: blank or non-list closes the list.
        if (next === undefined || next.trim() === "" || !/^\s/.test(next)) {
          closeLists();
        }
      }
      continue;
    }

    // Indented code block (4 spaces) — only when not in a list paragraph.
    if (/^( {4}|\t)\S/.test(line)) {
      flushPara();
      closeLists();
      const codeLines: string[] = [];
      while (i < lines.length && (/^( {4}|\t)/.test(lines[i] ?? "") || (lines[i] ?? "").trim() === "")) {
        if ((lines[i] ?? "").trim() === "") break;
        codeLines.push((lines[i] ?? "").replace(/^( {4}|\t)/, ""));
        i++;
      }
      html.push(`<div class="codeblock"><div class="code-head"><button type="button" class="copy-btn" data-code-copy title="Copy code">copy</button></div><pre><code>${codeLines.join("\n")}</code></pre></div>`);
      continue;
    }

    // Regular paragraph line.
    para.push(line.trim());
    i++;
  }

  flushPara();
  closeLists();
  return html.join("\n");
}

/** Heuristic: does this look like markdown worth rendering (vs plain text)? */
export function looksLikeMarkdown(s: string): boolean {
  return /(^|\n)#{1,6}\s|```|~~~|`[^`\n]+`|\*\*[^*\n]+\*\*|^>\s|\[(?:[^\]]+)\]\((?:[^)]+)\)|(^|\n)\s*([-*+]|\d+[.)])\s+\S|(^|\n)\|.+\|/.test(s);
}
